"""Type stubs for async I/O utilities."""

from pathlib import Path
from typing import Callable, List, Optional

async def read_file(path: Path) -> str: ...
async def write_file(path: Path, content: str) -> None: ...
async def ensure_dir(path: Path) -> None: ...
async def get_file_size(path: Path) -> Optional[int]: ...
async def is_dir(path: Path) -> bool: ...
async def path_exists(path: Path) -> bool: ...
async def count_lines(path: Path) -> int: ...
async def walk_directory(
    path: Path, ignore_func: Callable[[Path], bool]
) -> List[Path]: ...
